### PR TITLE
lib: fix a bug in mailbox

### LINKED ISSUE #349: Gatekeeper aborted due to too many requests
When testing Gatekeeper using the latest [test repo](https://github.com/cjdoucette/gatekeeper/tree/xia1_gk_test), Gatekeeper aborted due to too many requests.

```
GATEKEEPER: 13217475 log entries were suppressed at lcore 4 during the last ratelimit interval
GATEKEEPER SOL: Out of request bandwidth
GATEKEEPER SOL: Out of request bandwidth
PANIC in mb_alloc_entry():
line 86	assert "ret == 0" failed
PANIC in mb_alloc_entry():
line 86	assert "ret == 0" failed
GATEKEEPER SOL: Out of request bandwidth
GATEKEEPER SOL: Out of request bandwidth
GATEKEEPER SOL: Out of request bandwidth
GATEKEEPER SOL: Out of request bandwidth
GATEKEEPER SOL: Out of request bandwidth
GATEKEEPER SOL: Out of request bandwidth
GATEKEEPER SOL: Out of request bandwidth
GATEKEEPER SOL: Out of request bandwidth
12: [/lib/x86_64-linux-gnu/libc.so.6(clone+0x3f) [0x7f48a9b7388f]]
11: [/lib/x86_64-linux-gnu/libpthread.so.0(+0x76db) [0x7f48a9e4a6db]]
10: [./build/gatekeeper(eal_thread_loop+0x1f1) [0x56371b07a7b1]]
9: [./build/gatekeeper(+0x1ff0b6) [0x56371ac2a0b6]]
8: [./build/gatekeeper(+0x1fe15d) [0x56371ac2915d]]
7: [./build/gatekeeper(+0x1fd771) [0x56371ac28771]]
6: [./build/gatekeeper(+0x1fd5c0) [0x56371ac285c0]]
5: [./build/gatekeeper(+0x1e5511) [0x56371ac10511]]
4: [./build/gatekeeper(gk_solicitor_enqueue+0x5e) [0x56371ae19ca4]]
3: [./build/gatekeeper(mb_alloc_entry+0x2ca) [0x56371ae21f45]]
2: [./build/gatekeeper(__rte_panic+0xc5) [0x56371aac0bef]]
1: [./build/gatekeeper(rte_dump_stack+0x2e) [0x56371b081a4e]]
```

### PR DESCRIPTION
**Pull request by mengxiang0811**
When testing Gatekeeper under simulated DDoS attack with
repo https://github.com/cjdoucette/gatekeeper/tree/xia1_gk_test,
Gatekeeper aborted due to too many requests.

After tracing the call graph of the function call ``mb_alloc_entry()``,
we found that the documentation in both the DPDK documentation
http://doc.dpdk.org/api/rte__mempool_8h.html#a6150c041e889498a08d0e0d0769292cb
and its comment for function ``rte_mempool_get()`` were wrong: its return
value is either ``0`` or ``-ENOENT``. However, the true return value is either ``0``
or ``-ENOBUFS`` according to DPDK file ``drivers/mempool/ring/rte_mempool_ring.c``

This patch closes #349.

### CODE REVIEW

File: lib/mailbox.c [hunk 1]
```diff
@@ -78,7 +78,7 @@ mb_alloc_entry(struct mailbox *mb)
 {
 	void *obj = NULL;
 	int ret = rte_mempool_get(mb->pool, &obj);
-	if (ret == -ENOENT) {
+	if (ret < 0) {
 		G_LOG(ERR, "mailbox: not enough entries in the mempool\n");
```
Comment (AltraMayor) [inline lib/mailbox.c]: Given that the idea is to handle any error, we should update the error message and include the error code and `strerror(3)` of the error code.

**Comment by mengxiang0811** [comment]
This rebase is ready for another review.
