### PR TITLE
 net: check RSS hash key get updated correctly

### LINKED ISSUE #265: GK incorrectly calculates RSS hash in software
The GK block uses the RSS hash when doing flow lookups.

First, it uses it when receiving a packet on the front interface to do a flow lookup. For this one, it uses the RSS hash calculated by hardware:

https://github.com/AltraMayor/gatekeeper/blob/master/gk/main.c#L1389-L1390

Second, when Grantor sends Gatekeeper a decision regarding a flow (IP src, dst pari), the GK block calculates the RSS hash in software to then (lookup and) add that decision to the flow table:

https://github.com/AltraMayor/gatekeeper/blob/master/gk/main.c#L840-L841

It seems that the software hash does not match the hardware hash. I have an example where Gatekeeper receives a packet on the front interface, whose flow key (EtherType + IP pair) and RSS hash are:

```
flow key: 00 08 00 00 ac 1f 02 ab ac 20 04 c8 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
hash val: 3017585628
```

And when receiving a policy decision for this packet, its flow key and hash value is:

```
flow key: 00 08 00 00 ac 1f 02 ab ac 20 04 c8 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
hash val: 1787437985
```

The entry added to the hash table therefore will not be found when packets from this flow come into the front interface.

### PR DESCRIPTION
**Pull request by mengxiang0811**
This pull request closes #265

### CODE REVIEW

File: lib/net.c [hunk 1]
```diff
@@ -885,6 +890,51 @@ check_port_offloads(struct gatekeeper_if *iface,
 	if (iface->mtu > RTE_MBUF_DEFAULT_BUF_SIZE)
 		port_conf->txmode.offloads |= DEV_TX_OFFLOAD_MULTI_SEGS;
 
+	for (i = 0; i < iface->num_ports; i++) {
```
Comment (cjdoucette) [inline lib/net.c]: Would this loop be better placed in `check_port_rss()`?

File: lib/net.c [hunk 2]
```diff
@@ -885,6 +890,51 @@ check_port_offloads(struct gatekeeper_if *iface,
...
+		struct rte_eth_rss_conf cur_rss_conf;
+		uint16_t port_id = iface->ports[i];
+		int ret = rte_eth_dev_rss_hash_update(port_id, &rss_conf);
+		if (ret == 0)
+			continue;
+
+		ret = rte_eth_dev_rss_hash_conf_get(port_id, &cur_rss_conf);
+		if (ret < 0)
+			return ret;
```
Comment (cjdoucette) [inline lib/net.c]: Since returning an error here signals that Gatekeeper does not support a critical hardware capability, we should have an error message describing what capability is missing (here and in the error conditions below).

**Comment by mengxiang0811** [comment]
This rebase incorporated Cody's suggestions.

File: gk/main.c [hunk 3]
```diff
@@ -1385,14 +1386,17 @@ process_pkts_front(uint16_t port_front, uint16_t port_back,
...
-				!ipv6_configured_front)) {
+		if (unlikely((packet.flow.proto == ETHER_TYPE_IPv4 &&
+				!ipv4_configured_front) ||
+				(packet.flow.proto == ETHER_TYPE_IPv6 &&
+				!ipv6_configured_front))) {
 			drop_packet_front(pkt, instance);
 			continue;
 		}
 
+		ip_flow_hash_val = front->rss ? pkt->hash.rss :
```
Comment (AltraMayor) [inline gk/main.c]: Use `likely()` for the test.

File: gk/main.c [hunk 4]
```diff
@@ -1385,14 +1386,17 @@ process_pkts_front(uint16_t port_front, uint16_t port_back,
...
 		}
 
-		if (unlikely(packet.flow.proto == ETHER_TYPE_IPv4 &&
-				!ipv4_configured_front ||
-				packet.flow.proto == ETHER_TYPE_IPv6 &&
-				!ipv6_configured_front)) {
+		if (unlikely((packet.flow.proto == ETHER_TYPE_IPv4 &&
+				!ipv4_configured_front) ||
+				(packet.flow.proto == ETHER_TYPE_IPv6 &&
+				!ipv6_configured_front))) {
```
Comment (AltraMayor) [inline gk/main.c]: Please remove this fix, Cody is already working on this with a patch.

File: gk/main.c [hunk 5]
```diff
@@ -1665,10 +1669,10 @@ process_pkts_back(uint16_t port_back, uint16_t port_front,
...
 		}
 
-		if (unlikely(packet.flow.proto == ETHER_TYPE_IPv4 &&
-				!ipv4_configured_back ||
-				packet.flow.proto == ETHER_TYPE_IPv6 &&
-				!ipv6_configured_back)) {
+		if (unlikely((packet.flow.proto == ETHER_TYPE_IPv4 &&
+				!ipv4_configured_back) ||
+				(packet.flow.proto == ETHER_TYPE_IPv6 &&
+				!ipv6_configured_back))) {
```
Comment (AltraMayor) [inline gk/main.c]: Please remove this fix, Cody is already working on this with a patch.

File: lib/net.c [hunk 6]
```diff
@@ -720,10 +720,62 @@ get_if_back(struct net_config *net_conf)
...
+			memcmp(rss_conf->rss_key,
+			cur_rss_conf.rss_key,
+			rss_conf->rss_key_len) != 0))
+		return -EINVAL;
+
+	if (cur_rss_conf.rss_key_len > GATEKEEPER_RSS_KEY_LEN)
+		return -EINVAL;
+
+	/* Update the default RSS hash key. */
+	memset(default_rss_key, 0, RTE_DIM(default_rss_key));
```
Comment (AltraMayor) [inline lib/net.c]: `memset()` expects the size in bytes, so use `sizeof(default_rss_key)` instead of `RTE_DIM(default_rss_key)`. Notice that the type of the array `default_rss_key` is `uint8_t`, so both expressions are equivalent. But given the nature of `memset()`, `sizeof()` is preferable because it doesn't depend on the type.

File: lib/net.c [hunk 7]
```diff
@@ -720,10 +720,62 @@ get_if_back(struct net_config *net_conf)
...
+	rte_memcpy(default_rss_key, cur_rss_conf.rss_key,
+		cur_rss_conf.rss_key_len);
+
+	/* Convert RSS key. */
+	rte_convert_rss_key((uint32_t *)&default_rss_key,
+		(uint32_t *)rss_key_be,
+		RTE_DIM(default_rss_key));
```
Comment (AltraMayor) [inline lib/net.c]: 1. `check_port_rss_key_update()` is called on each port and `gatekeeper_init_network()` already calls `rte_convert_rss_key()`. So I think it's fine to drop the call to `rte_convert_rss_key()` here.
2. The call of `rte_convert_rss_key()` was copied from `gatekeeper_init_network()` and it seems to have two issues here:
2.1 Shouldn't we drop `&` from `(uint32_t *)&default_rss_key`?
2.2 `rte_convert_rss_key()` expects the size of `default_rss_key` in bytes, so use `sizeof(default_rss_key)`. Moreover, add `RTE_BUILD_BUG_ON(sizeof(default_rss_key % 4 != 0);` just before the call of `rte_convert_rss_key()` to guarantee that our key has a proper size.

Please add a patch for updating the call of `rte_convert_rss_key()` in `lib/net.c:gatekeeper_init_network()`.

File: lib/net.c [hunk 8]
```diff
@@ -720,10 +720,62 @@ get_if_back(struct net_config *net_conf)
...
+			rss_conf->rss_key_len) != 0))
+		return -EINVAL;
+
+	if (cur_rss_conf.rss_key_len > GATEKEEPER_RSS_KEY_LEN)
+		return -EINVAL;
+
+	/* Update the default RSS hash key. */
+	memset(default_rss_key, 0, RTE_DIM(default_rss_key));
+	rte_memcpy(default_rss_key, cur_rss_conf.rss_key,
+		cur_rss_conf.rss_key_len);
```
Comment (AltraMayor) [inline lib/net.c]: If we are updating the RSS key of the device with `default_rss_key` and checking it updated, why are we copying the current key to `default_rss_key`?

File: lib/net.c [hunk 9]
```diff
@@ -720,10 +720,62 @@ get_if_back(struct net_config *net_conf)
...
+	 * At least two ports with different RSS hash keys
+	 * cannot be updated.
+	 */
+	if (!*rss_key_updatable &&
+			(cur_rss_conf.rss_key == NULL ||
+			cur_rss_conf.rss_key_len !=
+			rss_conf->rss_key_len ||
+			memcmp(rss_conf->rss_key,
+			cur_rss_conf.rss_key,
+			rss_conf->rss_key_len) != 0))
```
Comment (AltraMayor) [inline lib/net.c]: Indent the parameter of `memcmp()`.

File: lib/net.c [hunk 10]
```diff
@@ -720,10 +720,62 @@ get_if_back(struct net_config *net_conf)
...
+			iface->name);
+		return ret;
+	}
+
+	/*
+	 * At least two ports with different RSS hash keys
+	 * cannot be updated.
+	 */
+	if (!*rss_key_updatable &&
+			(cur_rss_conf.rss_key == NULL ||
```
Comment (AltraMayor) [inline lib/net.c]: We fail whenever a single NIC cannot update its RSS key, so variable `rss_key_updatable` is not doing anything here. So we can drop it altogether.

File: lib/net.c [hunk 11]
```diff
@@ -720,10 +720,62 @@ get_if_back(struct net_config *net_conf)
 	ETH_RSS_NONFRAG_IPV6_OTHER | \
 	ETH_RSS_IPV6_EX)
 
+static int
+check_port_rss_key_update(struct gatekeeper_if *iface, uint16_t port_id,
+	bool *rss_key_updatable, struct rte_eth_rss_conf *rss_conf)
```
Comment (AltraMayor) [inline lib/net.c]: Add `const` to parameter `rss_conf` to guarantee that each port will see the same thing.

File: lib/net.c [hunk 12]
```diff
@@ -720,10 +720,62 @@ get_if_back(struct net_config *net_conf)
...
+{
+	struct rte_eth_rss_conf cur_rss_conf;
+	int ret = rte_eth_dev_rss_hash_update(port_id, rss_conf);
```
Comment (AltraMayor) [inline lib/net.c]: Once `rss_conf` becomes `const` (see another comment), get a local copy of `rss_conf` and pass it to `rte_eth_dev_rss_hash_update()`. It seems that DPDK's developers have forgotten to make the parameter `const`.

File: lib/net.c [hunk 13]
```diff
@@ -720,10 +720,62 @@ get_if_back(struct net_config *net_conf)
...
+			(cur_rss_conf.rss_key == NULL ||
+			cur_rss_conf.rss_key_len !=
+			rss_conf->rss_key_len ||
+			memcmp(rss_conf->rss_key,
+			cur_rss_conf.rss_key,
+			rss_conf->rss_key_len) != 0))
+		return -EINVAL;
+
+	if (cur_rss_conf.rss_key_len > GATEKEEPER_RSS_KEY_LEN)
+		return -EINVAL;
```
Comment (AltraMayor) [inline lib/net.c]: Since the test above this one already guarantees that `cur_rss_conf.rss_key_len == rss_conf->rss_key_len`, this test is not needed.

File: lib/net.c (hunk 8 above)
Comment (mengxiang0811) [reply lib/net.c]: The code comes from the assumption that Gatekeeper will abort only when at least two NICs with different hash keys cannot be updated, in which we cannot keep the hash keys consistent amog all the NICs.

If only one NIC's hash key cannot be updated, we can save it as the default, and update all other NICs' hash key later on.

File: lib/net.c (hunk 7 above)
Comment (mengxiang0811) [reply lib/net.c]: 2.1 Indeed, the code was initially copied from a [test example](https://github.com/cjdoucette/dpdk/blob/46a945c1a3bf5904cb88c28bf1e8c441e0536641/test/test/test_thash.c#L116-L117) from DPDK. I just found another [example](https://github.com/cjdoucette/dpdk/blob/46a945c1a3bf5904cb88c28bf1e8c441e0536641/lib/librte_eventdev/rte_event_eth_rx_adapter.c#L2003-L2005), which removes ``&`` from ``(uint32_t *)&default_rss_key``. By checking the [definition](https://github.com/cjdoucette/dpdk/blob/46a945c1a3bf5904cb88c28bf1e8c441e0536641/lib/librte_hash/rte_thash.h#L153-L160) of ``rte_convert_rss_key()``, I think you are right.

Comment (mengxiang0811) [reply lib/net.c]: I have run the [test example](https://github.com/cjdoucette/dpdk/blob/46a945c1a3bf5904cb88c28bf1e8c441e0536641/test/test/test_thash.c#L116-L117) with and without ``&``, both pass the tests. Here is an [explanation](https://stackoverflow.com/questions/8412694/address-of-array).

Comment (AltraMayor) [reply lib/net.c]: The link to the explanation was very useful. Thank you.

Let's have it without the `&`. The other form is unusual.

File: lib/net.c (hunk 8 above)
Comment (AltraMayor) [reply lib/net.c]: Well, in this case, the code is not doing what you are saying it should. For example, consider a case in which only one NIC does not support updating its RSS key:
1. `rte_eth_dev_rss_hash_update()` fails on the NIC that cannot update its key, what implies that `check_port_rss_key_update()` fails as well. `check_port_rss_key_update()` failing disables RSS altogether.
2. Even fixing item 1 above, variable `port_conf` will have the key that all NICs must use after the loop in `check_port_offloads()`, but Gatekeeper will later fail to update the NICs with that key because there is a NIC that doesn't support updating its key; it doesn't matter that is the same key it has.

Comment (mengxiang0811) [reply lib/net.c]: 1. if ``rte_eth_dev_rss_hash_update()`` fails on that NIC, the return value will be ``ret < 0``, which will not fail ``check_port_rss_key_update()`` directly, instead, it tries to obtain the RSS hash key of that NIC.

2. Good point! To avoid the failure, we may have to introduce another data structure for each port recording its updatable status. If we abort when one of the NICs cannot support update, the solution will be straightforward as you suggested in other comments.

Comment (AltraMayor) [reply lib/net.c]: I think that failing if any port doesn't support updating its RSS key is the way to go because ENA, our original target, does not allow either one to update, or to get the RSS key. That is, we are adding complexity to our code for a NIC that we don't even know if it exists: a NIC that gives its RSS key, but doesn't allow one to update it.

**Comment by mengxiang0811** [comment]
This rebase is ready for another review.

**Comment by AltraMayor** [comment]
Patch **net: update the call of rte_convert_rss_key()** has already been merged in another pull request. Please drop it from this pull request.

**Comment by AltraMayor** [comment]
My confusion reading GitHub cross-links. Disregard my previous message.

File: lib/net.c [hunk 14]
```diff
@@ -1391,13 +1448,42 @@ start_iface(struct gatekeeper_if *iface, unsigned int num_attempts_link_get)
...
 	}
 
 	/* Bonding port(s). */
 	if (iface_bonded(iface)) {
 		ret = start_port(iface->id, NULL, num_attempts_link_get);
 		if (ret < 0)
 			goto stop_partial;
+
+		if (check_port_rss_key_update(iface, iface->id)) {
+			G_LOG(ERR,
```
Comment (AltraMayor) [inline lib/net.c]: Since we already check per port above, do we really need to check for the bonded interface?

File: lib/net.c [hunk 15]
```diff
@@ -1365,6 +1373,55 @@ setup_ipv6_addrs(struct gatekeeper_if *iface)
...
+check_port_rss_key_update(struct gatekeeper_if *iface, uint16_t port_id)
+{
+	uint8_t rss_hash_key[GATEKEEPER_RSS_KEY_LEN];
+	struct rte_eth_rss_conf rss_conf = {
+		.rss_key = rss_hash_key,
+		.rss_key_len = GATEKEEPER_RSS_KEY_LEN,
+	};
+	int ret = rte_eth_dev_rss_hash_conf_get(port_id, &rss_conf);
+	if (ret != 0) {
+		switch (ret) {
```
Comment (AltraMayor) [inline lib/net.c]: Style: add `case 0:` with a single `break;` to avoid the `if` statement and unindent the `switch`. You'll need to replace the `break;` of the other cases with `return ret;`.

File: lib/net.c (hunk 14 above)
Comment (mengxiang0811) [reply lib/net.c]: I found there is a comment ``Bonded port inherits RSS and offload settings from the slave ports added to it`` in ``lib/net.c``, so I think we can drop this check.

**Comment by mengxiang0811** [comment]
This rebase is ready for another review.
