### PR TITLE
sol: have multiple blocks to spread the load from GK blocks

### LINKED ISSUE #374: Fail to enqueue requests to SOL's ring
When doing the performance evaluation, I occasionally found that the SOL block sometimes fails to enqueue all the requests to its ring. Some example outputs are shown below:

```
GATEKEEPER SOL: Failed to enqueue a bulk of 32 requests - only 0 requests are enqueued
GATEKEEPER SOL: Failed to enqueue a bulk of 12 requests - only 0 requests are enqueued
GATEKEEPER SOL: Failed to enqueue a bulk of 4 requests - only 0 requests are enqueued
GATEKEEPER SOL: Failed to enqueue a bulk of 32 requests - only 0 requests are enqueued
GATEKEEPER SOL: Failed to enqueue a bulk of 28 requests - only 0 requests are enqueued
GATEKEEPER SOL: Failed to enqueue a bulk of 4 requests - only 0 requests are enqueued
GATEKEEPER SOL: Failed to enqueue a bulk of 32 requests - only 0 requests are enqueued
GATEKEEPER SOL: Failed to enqueue a bulk of 16 requests - only 0 requests are enqueued
GATEKEEPER SOL: Failed to enqueue a bulk of 28 requests - only 0 requests are enqueued
GATEKEEPER SOL: Failed to enqueue a bulk of 32 requests - only 0 requests are enqueued
GATEKEEPER SOL: Failed to enqueue a bulk of 32 requests - only 0 requests are enqueued
GATEKEEPER SOL: Failed to enqueue a bulk of 32 requests - only 0 requests are enqueued
```

### PR DESCRIPTION
**Pull request by mengxiang0811**
This patch closes #374 and #185

### CODE REVIEW

File: gk/main.c [hunk 1]
```diff
@@ -2442,6 +2443,8 @@ gk_stage1(void *arg)
 		}
 		inst_ptr->tx_queue_back = ret;
 
+		instance->sol_inst = &sol_conf->instances[i % sol_conf->num_lcores];
```
Comment (AltraMayor) [inline gk/main.c]: We need to do something smarter here (and/or at the Lua configuration) in order to match the NUMA node of the GK blocks and their corresponding SOL block.

I don't have a solution, but it's better to discuss it before implementing it.

Comment (AltraMayor) [reply gk/main.c]: A solution would be for `struct gk_config` to have an array whose index is the instance and the value the index of the associated SOL instance. This solution pushes the association to the Lua code, so it can make the NUMA node match or any other match that we may want to try.

**Comment by mengxiang0811** [comment]
This rebase is ready for another review.

File: lua/main_config.lua [hunk 2]
```diff
@@ -36,19 +35,25 @@ function gatekeeper_init()
...
 		local gk_lcores =
 			staticlib.alloc_lcores_from_same_numa(numa_table,
-				n_lcores + 2)
-		local sol_lcore = table.remove(gk_lcores)
+				n_lcores + 1)
 		local ggu_lcore = table.remove(gk_lcores)
 
+		local n_sol_lcores = 1
+		local sol_lcores =
+			staticlib.alloc_lcores_from_same_numa(numa_table,
```
Comment (mengxiang0811) [inline lua/main_config.lua]: Once pull request #391 is merged, we need to spread the SOL blocks among the NUMA nodes using those functions.

**Comment by mengxiang0811** [comment]
This rebase incorporated pull request #391

File: lua/gatekeeper/staticlib.lua [hunk 3]
```diff
@@ -124,6 +124,38 @@ function convert_numa_table_to_array (numa_table)
...
 end
 
+function gk_sol_map (gk_lcores, sol_lcores)
+	local m = {}
+	local d = #gk_lcores / #sol_lcores
+	local sol_remaining_cap = {}
+
+	if #gk_lcores % #sol_lcores ~= 0 then
+		error("Wrong GK-to-SOL assignment");
+	end
```
Comment (AltraMayor) [inline lua/gatekeeper/staticlib.lua]: Shouldn't it just be a warning? Suppose that one needs 3 GK blocks on a two NUMA node machine. Since we'are going to allocate 2 SOL blocks, this test fails. But I think that the setup, although unbalanced, should be valid.

File: sol/main.c [hunk 4]
```diff
@@ -435,63 +430,98 @@ req_queue_init(struct sol_config *sol_conf)
...
+		/* Initialize token bucket as full. */
+		req_queue->tb_max_credit_bytes = round(max_credit_bytes_precise);
+		req_queue->tb_credit_bytes = req_queue->tb_max_credit_bytes;
+		req_queue->cycles_per_byte_floor = cycles_per_byte_precise;
+		req_queue->cycles_per_byte_a = a;
+		req_queue->cycles_per_byte_b = b;
+
+		/* Add integer number of cycles per byte to numerator. */
+		req_queue->cycles_per_byte_a +=
+			req_queue->cycles_per_byte_floor * req_queue->cycles_per_byte_b;
```
Comment (AltraMayor) [inline sol/main.c]: Can't these lines come before the `for` loop? It'd only require to update `a` once.

File: sol/main.c [hunk 5]
```diff
@@ -435,63 +430,98 @@ req_queue_init(struct sol_config *sol_conf)
...
 
-	SOL_LOG(NOTICE, "Cycles per byte (%f) represented as a rational: %"PRIu64" / %"PRIu64"\n",
-		cycles_per_byte_precise,
-		req_queue->cycles_per_byte_a, req_queue->cycles_per_byte_b);
+		SOL_LOG(NOTICE, "Cycles per byte (%f) represented as a rational: %"PRIu64" / %"PRIu64" at lcore %u\n",
+			cycles_per_byte_precise,
+			req_queue->cycles_per_byte_a, req_queue->cycles_per_byte_b,
+ 			sol_conf->lcores[i]);
```
Comment (AltraMayor) [inline sol/main.c]: This information is only need once for all SOL blocks since it doesn't change. Move this log entry before the `for` loop.

File: sol/main.c [hunk 6]
```diff
@@ -435,63 +430,98 @@ req_queue_init(struct sol_config *sol_conf)
...
+	int i;
 
-	list_for_each_entry_safe_m(entry, next, &req_queue->head) {
-		list_del(mbuf_to_list(entry));
-		rte_pktmbuf_free(entry);
-		req_queue->len--;
-	}
+	for (i = 0; i < sol_conf->num_lcores; i++) {
+		struct req_queue *req_queue = &sol_conf->instances[i].req_queue;
+		struct rte_mbuf *entry, *next;
```
Comment (AltraMayor) [inline sol/main.c]: Notice that `cleanup_sol()` may be called from `sol_stage1()`, so field `sol_conf->instances` may be `NULL`. This condition would trigger a segmentation fault here.

**Comment by mengxiang0811** [comment]
This rebase is ready for another review.

File: sol/main.c [hunk 7]
```diff
@@ -435,63 +430,105 @@ req_queue_init(struct sol_config *sol_conf)
...
+
+		/* Initialize token bucket as full. */
+		req_queue->tb_max_credit_bytes = round(max_credit_bytes_precise);
+		req_queue->tb_credit_bytes = req_queue->tb_max_credit_bytes;
+
+		/*
+		 * Initialize the number of cycles needed to credit
+		 * the request queue with bytes.
+		 */
+		req_queue->cycles_per_byte_floor = cycles_per_byte_precise;
```
Comment (AltraMayor) [inline sol/main.c]: Style: replace `cycles_per_byte_precise` with `cycles_per_byte_floor`.

File: sol/main.c [hunk 8]
```diff
@@ -435,63 +430,105 @@ req_queue_init(struct sol_config *sol_conf)
...
+		req_queue->cycles_per_byte_a = a;
+		req_queue->cycles_per_byte_b = b;
+
+		req_queue->time_cpu_cycles = rte_rdtsc();
```
Comment (AltraMayor) [inline sol/main.c]: Let's have a variable `now` and initialize all queues with the same clock.

File: sol/main.c [hunk 9]
```diff
@@ -504,14 +541,44 @@ static int
...
+		struct sol_instance *inst_ptr = &sol_conf->instances[i];
+		char ring_name[64];
+
+		ret = snprintf(ring_name, sizeof(ring_name), "sol_reqs_ring_%u",
+			i);
+		RTE_VERIFY(ret > 0 && ret < (int)sizeof(ring_name));
+
+		inst_ptr->ring = rte_ring_create(ring_name,
+			rte_align32pow2(sol_conf->pri_req_max_len),
+			rte_lcore_to_socket_id(sol_conf->lcore_id), RING_F_SC_DEQ);
```
Comment (AltraMayor) [inline sol/main.c]: Replace `sol_conf->lcore_id` with `lcore`.

File: sol/main.c [hunk 10]
```diff
@@ -504,14 +541,44 @@ static int
...
 {
 	struct sol_config *sol_conf = arg;
-	int ret = get_queue_id(&sol_conf->net->back, QUEUE_TYPE_TX,
-		sol_conf->lcore_id, NULL);
-	if (ret < 0) {
-		SOL_LOG(ERR, "Cannot assign a TX queue for the back interface for lcore %u\n",
-			sol_conf->lcore_id);
+	int ret, i;
+
+	sol_conf->instances = rte_calloc(__func__, sol_conf->num_lcores,
```
Comment (AltraMayor) [inline sol/main.c]: Use `rte_calloc_socket()` to be aligned with pull request #383.

I've looked for other cases to comment on, but I may have missed some spots, so please also review this patch for this kind of item.

File: config/static.c [hunk 11]
```diff
@@ -135,6 +135,76 @@ l_gk_assign_lcores(lua_State *l)
...
+	n = lua_objlen(l, 2); /* Get size of the table. */
+	if (n <= 0)
+		return 0; /* No results. */
+
+	ud = lua_newuserdata(l, sizeof(gk_sol_map));
+
+	lua_pushcfunction(l, protected_gk_assign_sol_map);
+	lua_insert(l, 1);
+
+	gk_sol_map = rte_malloc("gk_conf.gk_sol_map",
```
Comment (AltraMayor) [inline config/static.c]: Can't we use `rte_malloc_socket()` to be aligned with pull request #383?

File: config/static.c [hunk 12]
```diff
@@ -207,11 +277,85 @@ l_gt_assign_lcores(lua_State *l)
...
+	n = lua_objlen(l, 2); /* Get size of the table. */
+	if (n <= 0)
+		return 0; /* No results. */
+
+	ud = lua_newuserdata(l, sizeof(lcores));
+
+	lua_pushcfunction(l, protected_sol_assign_lcores);
+	lua_insert(l, 1);
+
+	lcores = rte_malloc("sol_conf.lcores", n * sizeof(*lcores), 0);
```
Comment (AltraMayor) [inline config/static.c]: Can't we use `rte_malloc_socket()` to be aligned with pull request #383?

File: sol/main.c [hunk 13]
```diff
@@ -419,10 +417,7 @@ req_queue_init(struct sol_config *sol_conf)
 			mbits_to_bytes(sol_conf->req_channel_bw_mbps);
 	}
 
-
```
Comment (AltraMayor) [inline sol/main.c]: I can't comment on line `if (sol_conf->req_channel_bw_mbps == 0) {` above, but could you write a new pull request to change the test to `<= 0`? This is a bug, so this new pull request can be quickly merged.

Comment (mengxiang0811) [reply sol/main.c]: Pull request #395 solves this issue.

File: sol/main.c (hunk 10 above)
Comment (mengxiang0811) [reply sol/main.c]: Thanks @AltraMayor ! In pull request #383 , we are assuming that all the GK blocks will be allocated on the same NUMA node. However, as we are now spreading the SOL blocks among the NUMA nodes, ideally, all the instances should be allocated according to its ``socket_id``.

File: include/gatekeeper_sol.h [hunk 14]
```diff
@@ -83,26 +83,39 @@ struct req_queue {
...
+	struct req_queue req_queue;
+} __rte_cache_aligned;
+
 /* Configuration for the Solicitor functional block. */
 struct sol_config {
-	unsigned int       lcore_id;
-
 	/* Maximum number of requests to store in priority queue at once. */
-	unsigned int       pri_req_max_len;
+	unsigned int        pri_req_max_len;
```
Comment (AltraMayor) [inline include/gatekeeper_sol.h]: This field is used in a number of places and, with multiple SOL blocks, its meaning has changed in some of those places. If we keep the code as it is now, we have the following bug: during an attack like the evaluation that we've been using, the ring of the SOL blocks may be able to hold more packets than the mbuf pools of the GK blocks have. In this case, GK blocks won't have mbufs ready for new packets until SOL blocks release them. Therefore, we need to divide this parameter per the number of SOL instances.

Given that this field is used in multiple places to address slightly different needs, it is better to rename it to get help from the compiler to identify all the places that need to be reviewed. Given that we may want to preserve the original name, just add the suffix `__`, so we can easily remove this suffix later.

Implement this comment first as a new patch in this pull request to simplify the review of it. Once we are happy with this new patch, we may decide to merge it into the current patch for coherence.

File: sol/main.c (hunk 10 above)
Comment (AltraMayor) [reply sol/main.c]: Pull request #383 is going to be merged before this pull request, so we must comply with pull request #383 here.

Notice that although the master branch is yet allocating all GK blocks on the same NUMA node, the code in pull request #383 doesn't require this assumption. The case in this comment thread is a problem that the GK blocks had to deal with as well, namely, the field `->instances` belongs to all instances. The code for GK block compromises and allocates the memory of this array in the same NUMA node of the first instance of the GK block. We can adopt this solution here as well.

**Comment by mengxiang0811** [comment]
This rebase is ready for another review.

**Comment by mengxiang0811** [comment]
This rebase refines the GK to SOL lcores mapping and is ready for review.

File: lua/sol.lua [hunk 15]
```diff
@@ -34,7 +34,7 @@ return function (net_conf, sol_lcores)
 
 	sol_conf.log_ratelimit_interval_ms = log_ratelimit_interval_ms
 	sol_conf.log_ratelimit_burst = log_ratelimit_burst
-	sol_conf.pri_req_max_len = pri_req_max_len
+	sol_conf.pri_req_max_len__ = pri_req_max_len / #sol_lcores
```
Comment (AltraMayor) [inline lua/sol.lua]: 1. We should keep the meaning of `pri_req_max_len` as a value per SOL instance; otherwise, the value of `pri_req_max_len__` may silently become very small as the number of instances grows. We had a similar problem with GK instances while Cody was working on the scanning of the flow table. So just drop `/ #sol_lcores` and let's adjust the code accordingly.

2. Let's also change the current value of `pri_req_max_len` from 1024 to 512 since our deployment will be with two NUMA nodes.

File: sol/main.c [hunk 16]
```diff
@@ -690,7 +690,7 @@ run_sol(struct net_config *net_conf, struct sol_config *sol_conf)
 	 * Although the packets are going to the back interface,
 	 * they are allocated at the front interface.
 	 */
-	front_inc = 2 * sol_conf->pri_req_max_len + sol_conf->enq_burst_size;
+	front_inc = 2 * sol_conf->pri_req_max_len__ + sol_conf->enq_burst_size;
```
Comment (AltraMayor) [inline sol/main.c]: We need to multiply this whole expression by the number of instances; see another comment for more information.

File: include/gatekeeper_sol.h (hunk 14 above)
Comment (AltraMayor) [reply include/gatekeeper_sol.h]: Thank you for creating the new patch, it has helped a lot to address this item.

**Comment by mengxiang0811** [comment]
This rebase is ready for another review.

**Comment by mengxiang0811** [comment]
This rebase is ready for another review.

File: lua/gatekeeper/staticlib.lua [hunk 17]
```diff
@@ -124,6 +124,41 @@ function convert_numa_table_to_array (numa_table)
...
+	local m = {}
+	local d = math.ceil(#gk_lcores / #sol_lcores)
+	local sol_remaining_cap = {}
+
+	if #gk_lcores % #sol_lcores ~= 0 then
+		print("Wrong GK-to-SOL assignment");
+	end
+
+	for i, v in ipairs(sol_lcores) do
+		table.insert(sol_remaining_cap, d)
```
Comment (AltraMayor) [inline lua/gatekeeper/staticlib.lua]: Notice that the code won't work for the case: 3 GK blocks and 2 NUMA nodes. Variable `d` is 1 in this case and only two entries are added to `sol_remaining_cap`. Although this case is unbalanced and already reported above in the code, we should support it anyway. A solution to address this issue goes as follows:

1. Rename `sol_remaining_cap` to `sol_allocated`;
2. Add zero instead of `d` to `sol_allocated`;
3. Discard variable `d`;
4. Instead of searching for the largest value in `sol_allocated` (see current test `sol_remaining_cap[i2] > sol_remaining[idx` later in the code), search for smallest;
5. Incrementing `sol_allocated` instead of decrementing it when a GK block is associated to a SOL block.

File: lua/gatekeeper/staticlib.lua [hunk 18]
```diff
@@ -124,6 +124,41 @@ function convert_numa_table_to_array (numa_table)
...
+		for i2, v2 in ipairs(sol_lcores) do
+			if rte_lcore_to_socket_id(v2) == socket_id and
+					(idx == nil or sol_remaining_cap[i2] >
+						sol_remaining[idx]) then
+				idx = i2
+			end
+		end
+
+		if idx == nil or sol_remaining_cap[idx] <= 0 then
+			error("Wrong GK-to-SOL assignment")
```
Comment (AltraMayor) [inline lua/gatekeeper/staticlib.lua]: Once the changes discussed in the other comments are implemented, the test should be only `idx == nil`, and the error message `"No Sol block allocated at NUMA node " .. socket_id`.

File: gk/main.c [hunk 19]
```diff
@@ -2442,6 +2443,8 @@ gk_stage1(void *arg)
 		}
 		inst_ptr->tx_queue_back = ret;
 
+		inst_ptr->sol_inst = &sol_conf->instances[gk_conf->gk_sol_map[i]];
```
Comment (AltraMayor) [inline gk/main.c]: The code should verify that `gk_conf->gk_sol_map[i]` is a valid index of `sol_conf->instances[]` (i.e. that it is greater or equal to zero and less than the number of SOL instances. We need to test it here because the Lua code could have a bug and pass an invalid map.

Comment (mengxiang0811) [reply gk/main.c]: When comparing ``gk_conf->gk_sol_map[i] >= 0``, an error will happen ``error: comparison of unsigned expression >= 0 is always true``.

Comment (AltraMayor) [reply gk/main.c]: Given that `gk_conf->gk_sol_map[i]` is an `unsigned int`, it's okay to skip the `>= 0` test.

File: lua/gatekeeper/staticlib.lua [hunk 20]
```diff
@@ -124,6 +124,40 @@ function convert_numa_table_to_array (numa_table)
...
+						sol_allocated[idx]) then
+				idx = i2
+			end
+		end
+
+		if idx == nil then
+			error("No SOL block allocated at NUMA node " .. socket_id)
+		end
+
+		m[i1] = idx
```
Comment (mengxiang0811) [inline lua/gatekeeper/staticlib.lua]: Shouldn't we assign ``m[i1] = idx - 1`` here? As in Lua, the index starts from ``1``.

File: gk/main.c (hunk 19 above)
Comment (AltraMayor) [reply gk/main.c]: Don't use `RTE_VERIFY()` here, have an `if` statement and deal as a regular error.

File: lua/gatekeeper/staticlib.lua (hunk 20 above)
Comment (AltraMayor) [reply lua/gatekeeper/staticlib.lua]: It's better to decrement `idx` in `protected_gk_assign_sol_map()` since we already decrement `i1` there as well. This way `m` behaves like a regular Lua array in the Lua code.

**Comment by mengxiang0811** [comment]
This rebase is ready for another review.

File: lua/gatekeeper/staticlib.lua (hunk 20 above)
Comment (AltraMayor) [reply lua/gatekeeper/staticlib.lua]: You've forgotten to decrement `idx` in `protected_gk_assign_sol_map()`.

Comment (mengxiang0811) [reply lua/gatekeeper/staticlib.lua]: Done.

**Comment by mengxiang0811** [comment]
This rebase is ready for another review.

File: gk/main.c [hunk 21]
```diff
@@ -2534,6 +2543,12 @@ run_gk(struct net_config *net_conf, struct gk_config *gk_conf,
 		goto out;
 	}
 
+	if (gk_conf->gk_sol_map == NULL) {
+		GK_LOG(ERR, "GK-to-SOL mapping initialization is required\n");
```
Comment (AltraMayor) [inline gk/main.c]: Better phrase: `"GK-to-SOL mapping is required for initialization\n"`

File: config/static.c [hunk 22]
```diff
@@ -135,6 +135,76 @@ l_gk_assign_lcores(lua_State *l)
...
+	n = lua_objlen(l, 2); /* Get size of the table. */
+	if (n <= 0)
+		return 0; /* No results. */
+
+	ud = lua_newuserdata(l, sizeof(gk_sol_map));
+
+	lua_pushcfunction(l, protected_gk_assign_sol_map);
+	lua_insert(l, 1);
+
+	gk_sol_map = rte_calloc("gk_conf.gk_sol_map", n,
```
Comment (AltraMayor) [inline config/static.c]: Why `rte_calloc()` instead of `rte_malloc()` as used in similar functions? `gk_sol_map` is only returned at the end of `protected_gk_assign_sol_map()` when it was fully filled in and all went well.

**Comment by mengxiang0811** [comment]
This rebase is ready for another review.

File: lua/gatekeeper/staticlib.lua [hunk 23]
```diff
@@ -124,6 +124,40 @@ function convert_numa_table_to_array (numa_table)
...
+function gk_sol_map (gk_lcores, sol_lcores)
+	local m = {}
+	local sol_allocated = {}
+
+	if #gk_lcores % #sol_lcores ~= 0 then
+		print("Warning: uneven GK-to-SOL blocks assignment");
+	end
+
+	for i, v in ipairs(sol_lcores) do
+		table.insert(sol_allocated, 0)
```
Comment (AltraMayor) [inline lua/gatekeeper/staticlib.lua]: Style: `sol_allocated[i] = 0`

File: lua/main_config.lua [hunk 24]
```diff
@@ -40,19 +40,24 @@ function gatekeeper_init()
...
 			staticlib.alloc_lcores_evenly_from_all_numa_nodes(numa_table,
-				n_lcores, 0)
-		local gk_lcores = staticlib.convert_numa_table_to_array(gk_lcores_tbl)
-		local sol_lcore = staticlib.alloc_an_lcore(aux_numa_table)
+				n_gk_lcores, n_sol_lcores_per_socket)
+		local gk_lcores = staticlib.convert_numa_table_to_array(
+			staticlib.alloc_lcores_evenly_from_all_numa_nodes(lcores_table,
+				n_gk_lcores, 0))
+		local sol_lcores = staticlib.convert_numa_table_to_array(lcores_table)
 		local ggu_lcore = staticlib.alloc_an_lcore(aux_numa_table)
```
Comment (AltraMayor) [inline lua/main_config.lua]: Style: move the line above between the lines snown below to group all the GGU initialization:
```Lua
local gguf = require("ggu")
local ggu_conf = gguf(net_conf, gk_conf, ggu_lcore)
```

File: sol/main.c [hunk 25]
```diff
@@ -617,31 +690,29 @@ run_sol(struct net_config *net_conf, struct sol_config *sol_conf)
...
-		rte_lcore_to_socket_id(sol_conf->lcore_id), RING_F_SC_DEQ);
-	if (sol_conf->ring == NULL) {
-		G_LOG(ERR,
-			"mailbox: can't create ring sol_reqs_ring at lcore %u\n",
-			sol_conf->lcore_id);
-		ret = -1;
-		goto burst;
-	}
+	if (sol_conf->num_lcores <= 0)
+		goto out;
```
Comment (AltraMayor) [inline sol/main.c]: These lines must come earlier in order to use the label `out`. Here, it would require the label `burst`.

**Comment by mengxiang0811** [comment]
This rebase is ready for another review.

File: sol/main.c (hunk 25 above)
Comment (AltraMayor) [reply sol/main.c]: Why not moving this test before the burst section and keep the label `out`? the code reads simpler this way.

Comment (mengxiang0811) [reply sol/main.c]: Agreed. Done.

**Comment by mengxiang0811** [comment]
This rebase incorporated the latest merged pull request.

File: lua/gatekeeper/staticlib.lua [hunk 26]
```diff
@@ -124,6 +124,40 @@ function convert_numa_table_to_array (numa_table)
...
+		end
+
+		if idx == nil then
+			error("No SOL block allocated at NUMA node " .. socket_id)
+		end
+
+		m[i1] = idx
+		sol_allocated[idx] = sol_allocated[idx] + 1
+	end
+	return m
```
Comment (AltraMayor) [inline lua/gatekeeper/staticlib.lua]: Before returning, iterate over `sol_allocated` and report as warnings any lcore that has zero GK block allocated to it. These warnings will inform operators of lcore waste.

File: lua/main_config.lua [hunk 27]
```diff
@@ -40,21 +40,25 @@ function gatekeeper_init()
 	local gt_conf
 
 	if gatekeeper_server == true then
-		local n_lcores = 2
-		local gk_lcores_tbl =
+		local n_gk_lcores = 2
```
Comment (AltraMayor) [inline lua/main_config.lua]: Set `n_gk_lcores` with the following expression: `2 * staticlib.count_numa_nodes(numa_table)`, and add the following comment just above it:
```Lua
-- The following expression to set the number of GK block instances is a good recommendation, but it may not be optimal for all cases.
``` 
Break the comment into multiple lines as needed. And add the following protection afterwards:
```Lua
if n_gk_lcores <= 0 then
	error("No GK block allocated for Gatekeeper server")
end
```

**Comment by mengxiang0811** [comment]
This rebase is ready for another review.

File: lua/sol.lua [hunk 28]
```diff
@@ -28,6 +28,8 @@ return function (net_conf, lcore)
 		error("Failed to allocate sol_conf")
 	end
 
+	staticlib.sol_assign_lcores(sol_conf, sol_lcores)
```
Comment (AltraMayor) [inline lua/sol.lua]: I can't comment on the line above: `local sol_conf = staticlib.c.alloc_sol_conf(lcore)`. However, it must be updated as well as the Lua definition of `staticlib.c.alloc_sol_conf()`.

File: gk/main.c [hunk 29]
```diff
@@ -2403,6 +2403,7 @@ gk_stage1(void *arg)
 	for (i = 0; i < gk_conf->num_lcores; i++) {
 		unsigned int lcore = gk_conf->lcores[i];
 		struct gk_instance *inst_ptr = &gk_conf->instances[i];
+		struct sol_config *sol_conf = gk_conf->sol_conf;
```
Comment (AltraMayor) [inline gk/main.c]: Style: although variable `sol_conf` is only used inside of this `for` loop, its value doesn't change. So define it within the outside scope (i.e. at the beginning of `gk_stage1()`), and assign its value just before the `for` loop.

**Comment by mengxiang0811** [comment]
This rebase is ready for another review.

File: sol/main.c [hunk 30]
```diff
@@ -504,14 +544,45 @@ static int
...
+		RTE_VERIFY(ret > 0 && ret < (int)sizeof(ring_name));
+
+		inst_ptr->ring = rte_ring_create(ring_name,
+			rte_align32pow2(sol_conf->pri_req_max_len),
+			rte_lcore_to_socket_id(lcore), RING_F_SC_DEQ);
+		if (inst_ptr->ring == NULL) {
+			G_LOG(ERR,
+				"sol: can't create ring sol_reqs_ring at lcore %u\n",
+				lcore);
+			ret = -1;
```
Comment (AltraMayor) [inline sol/main.c]: This assignment of variable `ret` is not being used. In fact, the declaration of `ret` should be done within the `for` loop since it's only used inside of the loop.

File: sol/main.c [hunk 31]
```diff
@@ -504,14 +544,45 @@ static int
...
+		ret = get_queue_id(&sol_conf->net->back, QUEUE_TYPE_TX,
+			lcore, NULL);
+		if (ret < 0) {
+			SOL_LOG(ERR, "Cannot assign a TX queue for the back interface for lcore %u\n",
+				lcore);
+			goto cleanup;
+		}
+		inst_ptr->tx_queue_back = ret;
+
+		INIT_LIST_HEAD(&inst_ptr->req_queue.head);
```
Comment (AltraMayor) [inline sol/main.c]: This line should be moved to the `for` loop in `req_queue_init()` since this function is responsible for the initialization of the request queues. But adding the following comment here is of a good touch:
`/* @inst_ptr->req_queue is initialized at sol_stage2()/req_queue_init(). */`

**Comment by mengxiang0811** [comment]
This rebase is ready for another review.

File: sol/main.c (hunk 30 above)
Comment (AltraMayor) [reply sol/main.c]: You've forgotten to drop the line `ret = -1;` shown above.

Comment (mengxiang0811) [reply sol/main.c]: Thanks! Done.
